{{- if (not .Values.auth.existingSecret) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
    {{- if .Values.auth.password }}
    password: {{ .Values.auth.password | b64enc | quote }}
    {{ else }}
    password: {{ randAlphaNum 10 | b64enc | quote }}
    {{- end}}
    username: {{ .Values.auth.username | b64enc | quote }}
{{- end }}
